// PUBLIC VALUES ONLY. Never put Stripe secret keys, Supabase service-role keys,
// Anthropic keys, or distributor credentials in this file.
window.STUDIO365_CONFIG = {
  PRODUCT_NAME: "STUDIO365",
  SUPABASE_URL: "REPLACE_WITH_SUPABASE_URL",
  SUPABASE_ANON_KEY: "REPLACE_WITH_SUPABASE_ANON_KEY",
  STRIPE_PUBLISHABLE_KEY: "REPLACE_WITH_STRIPE_PUBLISHABLE_KEY",
  EDGE_FN_URL: "REPLACE_WITH_SUPABASE_EDGE_FUNCTION_BASE_URL"
};
